#       database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
#       jpa orm options
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect