#       database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
#       jpa orm options
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    database-change-log-lock-table: CHANGELOCK
    database-change-log-table: CHANGELOG
#        jwt auth
jwt:
  expiration: 99999
  secret: minecraft
  header: Authorization
password:
  hash:
    strength: 12