package by.zelezinsky.reservationsystembooking.security;

public interface Authorities {
    String VIEW_CITY = "VIEW_CITY";
    String UPDATE_CITY = "UPDATE_CITY";
    String DELETE_CITY = "DELETE_CITY";
    String VIEW_COUNTRY = "VIEW_COUNTRY";
    String UPDATE_COUNTRY = "UPDATE_COUNTRY";
    String DELETE_COUNTRY = "DELETE_COUNTRY";
    String VIEW_EVENT = "VIEW_EVENT";
    String UPDATE_EVENT = "UPDATE_EVENT";
    String DELETE_EVENT = "DELETE_EVENT";
    String VIEW_ESTABLISHMENT = "VIEW_ESTABLISHMENT";
    String UPDATE_ESTABLISHMENT = "UPDATE_ESTABLISHMENT";
    String DELETE_ESTABLISHMENT = "DELETE_ESTABLISHMENT";
    String VIEW_OFFER_CATEGORY = "VIEW_OFFER_CATEGORY";
    String UPDATE_OFFER_CATEGORY = "UPDATE_OFFER_CATEGORY";
    String DELETE_OFFER_CATEGORY = "DELETE_OFFER_CATEGORY";
    String VIEW_RESERVATION_OFFER = "VIEW_RESERVATION_OFFER";
    String UPDATE_RESERVATION_OFFER = "UPDATE_RESERVATION_OFFER";
    String DELETE_RESERVATION_OFFER = "DELETE_RESERVATION_OFFER";
    String VIEW_RESERVATION_UNIT_TYPE = "VIEW_RESERVATION_UNIT_TYPE";
    String UPDATE_RESERVATION_UNIT_TYPE = "UPDATE_RESERVATION_UNIT_TYPE";
    String DELETE_RESERVATION_UNIT_TYPE = "DELETE_RESERVATION_UNIT_TYPE";
    String VIEW_RESERVATION = "VIEW_RESERVATION";
    String UPDATE_RESERVATION = "UPDATE_RESERVATION";
    String DELETE_RESERVATION = "DELETE_RESERVATION";  
    String VIEW_RESERVATION_UNIT = "VIEW_RESERVATION_UNIT";
    String UPDATE_RESERVATION_UNIT = "UPDATE_RESERVATION_UNIT";
    String DELETE_RESERVATION_UNIT = "DELETE_RESERVATION_UNIT"; 
    String VIEW_RESERVATION_UNITED_PART = "VIEW_RESERVATION_UNITED_PART";
    String UPDATE_RESERVATION_UNITED_PART = "UPDATE_RESERVATION_UNITED_PART";
    String DELETE_RESERVATION_UNITED_PART = "DELETE_RESERVATION_UNITED_PART";
    String VIEW_ROLE = "VIEW_ROLE";
    String UPDATE_ROLE = "UPDATE_ROLE";
    String DELETE_ROLE = "DELETE_ROLE";
    String VIEW_USER = "VIEW_USER";
    String UPDATE_USER = "UPDATE_USER";
    String DELETE_USER = "DELETE_USER";

}
